#!/bin/bash

current_workspace=`i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name' | cut -d"\"" -f2`

echo $current_workspace

case $current_workspace in
	'1') new_workspace=2;;
	'2') new_workspace=3;;
	'3') exit ;;
	'4') new_workspace=5;;
	'5') new_workspace=6;;
	'6') exit ;;
	'7') new_workspace=8;;
	'8') new_workspace=9;;
	'9') exit ;;
	*)
		echo $current_workspace
		new_workspace=10
		;;
esac

i3-msg workspace $new_workspace
~/.config/i3/notify "Workspace $new_workspace"
