#
# ~/.bashrc
#
export EDITOR=/usr/bin/vim
if [ -d '/opt/android-sdk' ]; then
	export ANDROID_HOME=/opt/android-sdk
fi
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'

BYELLOW='\[\033[0;33m\]'
PS_CLEAR='\[\033[0m\]'
export PS1="${BYELLOW}[\w]${PS_CLEAR}\$ "

if [ -f ~/.profile ]; then
    source ~/.profile
fi

function cdls {
	if [ "$#" = 0 ]; then
		cd ~ 2>/dev/null && ls
	else
		cd "$@" && ls
	fi
}
alias cd="cdls"
