set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'mbbill/undotree'
Plugin 'scrooloose/syntastic'
Plugin 'Valloric/YouCompleteMe'
Plugin 'altercation/vim-colors-solarized'

call vundle#end()

filetype plugin indent on
syntax on
set relativenumber
set number
set hls
set undodir=$HOME/.VIM_UNDO_FILES
set undofile
set undolevels=5000
set pastetoggle=<F2>
set magic "Something cool? (Regular expressions?)"
set viminfo='100,<500,s50
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
color solarized
set background=dark
"Set tabs to 4 spaces
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

"Makes you be able to move around on wrapping lines
noremap j gj
noremap k gk
map <F3> :UndotreeToggle
cmap w!! w !sudo tee > /dev/null %

let g:syntatic_always_populate_loc_list = 1
let g:syntatic_auto_loc_list = 1
let g:syntatic_check_on_open = 1
let g:syntatic_check_on_wq = 0

"Set prolog syntax highlighting
au BufReadPost *.pro set syntax=prolog
