if [ -f $HOME/.zsh/motd ]; then
    source ~/.zsh/motd
fi

if [ -f ~/.profile ]; then
    source ~/.profile
fi

export JAVA_HOME='/usr/lib/jvm/java-8-jdk'
export EDITOR="/usr/bin/vim"
export MAKEFLAGS="-j$(expr $(nproc) \+ 1)"

alias override='sudo $(fc -ln -1)'
alias sl='ls --color=auto'
alias :q='exit'
alias viewnetwork='sudo arp-scan --interface=wlp2s0 --localnet'
alias getip="ifconfig | grep inet | grep broadcast | awk "\''{print$2}'\'
alias nolonglines="sed '/^.\{500\}./d'"
#alias poweroff="/usr/bin/systemctl poweroff"
#alias reboot="/usr/bin/systemctl reboot"
alias sc='systemctl'

#Add syntax highlighting in cat if available
which highlight 1>/dev/null 2>/dev/null
if [ $? -eq 0 ]; then
    alias cat="highlight -O ansi --stdout --force"
    alias cat2="/bin/cat"
fi

#Make cd do an ls afterwards
cdls() {
    new_directory="$*";
    if [ $# -eq 0 ]; then 
        new_directory=${HOME};
    fi;
    if [ ! -z $1 ] && [ $1 = cd ] && [ ! -z $2 ]; then
        builtin cd $2 2>/dev/null
        if [ $? -eq 0 ]; then
            ls --color=auto
        else
            echo no such file or directory: $2
        fi
    else
        builtin cd $new_directory 2>/dev/null
        if [ $? -eq 0 ]; then
            ls --color=auto
        else
            echo no such file or directory: $1
        fi
    fi
}
alias cd='cdls'

kj () {
        job="$(jobs -l | awk '{print $3}' | tail -n1)"
        if [ "$job" != "" ]
        then
                kill $job && fg
        fi
}

#Load oh-my-zsh libraries
for config_file ($HOME/.zsh/lib/*.zsh); do
    source $config_file
done

#Set the theme
if [ $UID -ne 0 ]; then
    ZSH_THEME="eastwood"
else
    ZSH_THEME="clean"
fi
source "$HOME/.zsh/themes/$ZSH_THEME.zsh-theme"

#Load plugins
source $HOME/.zsh/plugins/zsh-autosuggestions.zsh #Add autosuggetions
source $HOME/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh #Add syntax highlighting
source $HOME/.zsh/plugins/bash.command-not-found #Add insults
