#! /bin/bash

sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config split_ratio             0.5
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true
bspc config border_width            2
bspc config window_gap              0
bspc config focus_follows_pointer   true
bspc config center_pseudo_tiled     true
bspc config single_monocle          true
bspc config adaptative_raise        true
bspc config focused_border_color '#4C7899'
bspc config normal_border_color '#333333'
bspc config focused_locked_border_color '#28A017'
bspc config normal_locked_border_color '#8C8C8C'
bspc config presel_border_color '#F9F9F9'

bspc rule -a Gthumb state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a qt5ct state=floating
bspc rule -a Gsimplecal state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Grub-customizer state=floating
bspc rule -a Guake state=floating focus=on sticky=on layer=above
bspc rule -a guake floating=on focus=on sticky=on layer=abovebspc rule -a guake floating=on focus=on sticky=on
bspc rule -a Xarchiver state=pseudo_tiled
bspc rule -a Eog state=floating
bspc rule -a Gnome-disks state=floating
bspc rule -a Gpick state=floating
bspc rule -a Dconf-editor state=floating
bspc rule -a Bspwm:presel_feedback border_width=5

bspc config external_rules_command  ~/.config/bspwm/external_rules.sh

nitrogen --restore &
thunar --daemon &
guake &
jgmenu --at-pointer --hide-on-startup &
pnmixer &
nm-applet &
xfce4-power-manager &
synclient HorizTwoFingerScroll=1 &
synclient TapButton1=1 &
twmnd &
xfce4-clipman &
kdeconnect-indicator &
gnome-keyring-daemon &
sleep 5 && tint2 &
