#!/bin/bash


monitor=$(i3-msg -t get_outputs | jq '.[] | select(.active == true and .current_workspace == '`i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name'`') | .name' | cut -d"\"" -f2)

current_workspace=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name' | cut -d"\"" -f2 | tr ':' ' ' | awk '{if(length($2) == 0) {print $1;} else {print $2;}}')

echo $monitor":"$current_workspace

case $current_workspace in
	'1') exit ;;
	'2') new_workspace=1;;
	'3') new_workspace=2;;
	'4') exit ;;
	'5') new_workspace=4;;
	'6') new_workspace=5;;
	'7') exit ;;
	'8') new_workspace=7;;
	'9') new_workspace=8;;
	*)
		echo $current_workspace
		new_workspace=10
		;;
esac


new_workspace=$monitor":"$new_workspace
i3-msg move container to workspace $new_workspace
i3-msg workspace $new_workspace
~/.config/i3/notify "Workspace $new_workspace"
