#!/bin/bash
touchpads=$(xinput --list | grep -i touchpad | sed -E 's/^.*id=([0-9]+).*/\1/g')

for i in $touchpads; do
    enabled=$(xinput --list-props $i | grep -i "device enabled" | sed -E 's/.*\b([0-9]+)/\1/g')
    if (( $enabled == 0 )); then
        xinput --enable $i
        ~/.config/i3/notify "Touchpad is now on"
    else
        xinput --disable $i
        ~/.config/i3/notify "Touchpad is now off"
    fi
done
